name: Auto Tag from pyproject.toml

on:
  push:
    branches:
      - main

permissions:
  contents: write   # <-- Grant write access to contents (required to push a tag)

jobs:
  tag-from-pyproject:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Extract version
        id: version
        run: |
          version=$(python -c "import tomllib; data=tomllib.load(open('pyproject.toml','rb')); print(data['project']['version'])")
          echo "Found version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create and push tag if needed
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo "Discovered version: $VERSION"
          if [ -z "$VERSION" ]; then
            echo "No version found in pyproject.toml!"
            exit 1
          fi

          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag v$VERSION already exists. Doing nothing."
          else
            echo "Creating and pushing tag v$VERSION..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag "v$VERSION"
            git push origin "v$VERSION"
            echo "Pushed tag v$VERSION."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
